### ISSUE TITLE
Cloudinary resource not found

### ISSUE THREAD

**Issue by vcavallo** [0sc/activestorage-cloudinary-service#16]
Thanks for creating an activestorage cloudinary service! I wish I could say everything is working perfectly for me :) I have a feeling it's a cloudinary issue, but I'll drop it here first:
I'm getting `Resource not found - [TheLongCloudinaryKey].jpeg` on all my images, despite the fact that they're there in the media library and `TheLongCloudinaryKey` matches.

The request being generated by the template looks like this: 

```
https://api.cloudinary.com/v1_1/nyta/raw/download?api_key=[API KEY]&attachment=false&expires_at=1539659024&format=jpeg&public_id=d9uo9eTP1bcKwdeWLjZK6ZmQ.jpeg&signature=[SOME SIGNATURE]&timestamp=1539658724&type=upload
```

Does that look like the right request is being built? I've tried using `url_for` and `rails_blob_path` with the same result.
Any ideas would be much appreciated. Thanks!

**Comment by vcavallo** [comment]
I also should have mentioned that everything about **uploading** works just fine!

**Comment by vcavallo** [comment]
I'm half-asleep and stupid now, but so far my ideas are:
-

**Comment by 0sc** [comment]
I'm closing this as a possible issue with the cloudinary config. Please feel free to reopen if that's not the case.

**Comment by mansoorkhan108** [comment]
I am facing the same issue, @vcavallo did you found what causing it?

**Comment by 0sc** [comment]
@mansoorkhan108 can you share steps to reproduce?
