### ISSUE TITLE
How do you apply transformations?

### ISSUE THREAD

**Issue by iraszl** [0sc/activestorage-cloudinary-service#18]
Thanks for the helpful gem!

I can successfully upload to CL and then display the images with:
`<%= image_tag @user.image %>`

However, for the life of me I can't figure out how to pass in parameters so I can apply transformations, which is one of the key benefits of using CL. Example transformation is :width => 200 that you should be able pass in to resize to 200px.

An alternative solution would be if one knew the name of the file generated on CL, but I'm not sure how you can get that back from CL. This works for example:
`<%= cl_image_tag("pMYPkLpbjQW59LhxgHXSmhAv", :width => 200) %>`

Any guideance would be greatly appreciated.

**Comment by 0sc** [comment]
Please see discussions in #5

**Comment by 0sc** [comment]
Closing as duplicate
