### ISSUE TITLE
Direct upload not working

### ISSUE THREAD

**Issue by morgoth** [0sc/activestorage-cloudinary-service#2]
Hey.
I tried to use direct upload. I changed the "PUT" method to "POST" (as pointed in the readme), but I still cannot upload images directly.
I'm getting 401 from Cloudinary and I'm not sure why.

Url looks something like this:
`https://api.cloudinary.com/v1_1/wojtek-w/auto/upload?api_key=may-api-key&attachment=false&expires_at=1518098256&public_id=UNEbp3r5HSPABaaTdMVrk71o&signature=some-signature&timestamp=1518097956&type=upload`

Where you able to make it work at all?

**Comment by 0sc** [comment]
Hi @morgoth, this is a known issue highlighted [here](https://github.com/0sc/activestorage-cloudinary-service#known-issues) in the readme. The gist of it is: activestorage expects direct upload endpoints to accept PUT requests and cloudinary doesn't have such endpoint (see API reference [here](https://cloudinary.com/documentation/image_upload_api_reference#upload)). 

I don't think the readme has any such suggestion of `changing the "PUT" method to "POST"`. If you could point me to it, I'll love to update it avoid any confusion. 

In any case, once there's an amenable change to resolve this from either activestorage or cloudinary, I'll make the appropriate update.

**Comment by sodapopcan** [comment]
Just to be clear, @0sc, when you say client-side uploading doesn't work, does that mean it you can't uploaded via a form or are you simply talking about direct upload.

When I upload via a `f.file_field` the `cl_image_tag` returns something like this:

```
http://res.cloudinary.com/xxxxxxxxx/image/upload/%23%3CActiveStorage::Attached::One:0x00000000040faab0%3E
```

Just trying to figure out if this is this error or I'm doing something else wrong.

**Comment by sodapopcan** [comment]
Ah yes, which I'm realizing now if I just do a regular `file_field` it uploads to local storage.

**Comment by sodapopcan** [comment]
Ok, it's actually working fine.  I was confused when inspcting the URL that it looked it was coming from my heroku server but it's actually masking the cloudinary URL.  My apologies for such hasty reporting and thanks for the gem!

**Comment by 0sc** [comment]
Glad you resolved it @sodapopcan 👍 

Do you think there's any clarification required in the readme to ensure someone else doesn't hit same confusion?

**Comment by sodapopcan** [comment]
I dunno, maybe just clarify "client side upload" means "direct upload"?  I mean, that should be pretty obvious as it is but I've always heard it referred to as "direct".  It's really more of a brain fart on my end and my inexperience with Active Storage (this is my first time trying it out).

**Comment by murdoch** [comment]
Is this still an issue? Do client/direct uploads work yet?

**Comment by 0sc** [comment]
Yea, @murdoch, it's still open. Will close this once a fix is available

**Comment by ghost** [comment]
Any news on this? Experiencing this now with the direct uploads using the new ActionText editor.

Error looks like this:

`{"error":{"message":"Invalid Signature *************************. String to sign - 'public_id=*************************&timestamp=1569997462&type=upload'."}}`

**Comment by omkz** [comment]
> Any news on this? Experiencing this now with the direct uploads using the new ActionText editor.
> 
> Error looks like this:
> 
> `{"error":{"message":"Invalid Signature *************************. String to sign - 'public_id=*************************&timestamp=1569997462&type=upload'."}}`

Have you found the solution? I have the same issue.

**Comment by omkz** [comment]
> Any news on this? Experiencing this now with the direct uploads using the new ActionText editor.
> 
> Error looks like this:
> 
> `{"error":{"message":"Invalid Signature *************************. String to sign - 'public_id=*************************&timestamp=1569997462&type=upload'."}}`
Have you found the solution? I have the same issue.

**Comment by omkz** [comment]
> Any news on this? Experiencing this now with the direct uploads using the new ActionText editor.
> 
> Error looks like this:
> 
> `{"error":{"message":"Invalid Signature *************************. String to sign - 'public_id=*************************&timestamp=1569997462&type=upload'."}}`

Have you found the solution? I have the same issue.

**Comment by ghost** [comment]
@omkz no, but we went for a workaround.

Modified actiontext/trix attachment events to:
- send attached files to our app's server
- from the server, upload to Cloudinary via active_storage
- return file's Cloudinary url to the editor and display

Still behaves like it's a direct upload but is not, but this worked for us.
