### ISSUE TITLE
AnalyzeJob failing when Cloudinary Strict transformations are turned on

### ISSUE THREAD

**Issue by MichalRemis** [0sc/activestorage-cloudinary-service#22]
When Cloudinary's console _Strict transformations_ are turned on, AtiveStorage's `AnalyzeJob` is failing again and again, slowly depleting Cloudinary bandwitch. It is because of  the way `activestorage-cloudinary-service` is downloading image for analyzing (more info here https://github.com/cloudinary/cloudinary_gem/issues/328).

Workaround to make this work is to explicitly enable `no extension` transformation in Cloudinary's console.

 But I think it should work without needing this by default. Download url should be signed by using `sign_url: true` parameter

**Comment by 0sc** [comment]
Hey MichalRemis thanks for reporting this. I'll investigate and get back to you
