### ISSUE TITLE
Error while calling ActiveStorage::Blob#download if Net::HTTP wasn´t loaded before

### ISSUE THREAD

**Issue by ignaciovillaverde** [0sc/activestorage-cloudinary-service#29]
I am getting a `NameError: uninitialized constant Net::HTTP` when calling `ActiveStorage::Blob#download` if `Net::HTTP` was not loaded before.

This is being called at `active_storage/service/cloudinary_service.rb:123`.

For solving it now I am requiring it on my application.rb by calling `require "net/http"`.

Any ideas?
Thank you.

**Comment by 0sc** [comment]
Do you mind trying with the official [cloudinary](https://github.com/cloudinary/cloudinary_gem) gem? It now has support for active_storage hence I'll be archiving this soon.

**Comment by ignaciovillaverde** [comment]
Thank you very much.
