### ISSUE TITLE
open will return a StringIO if the file is small enough, and that breaks File.open

### ISSUE THREAD

**Issue by MadonnaMat** [0sc/activestorage-cloudinary-service#3]
https://github.com/0sc/activestorage-cloudinary-service/blob/747d916c0fe5681b265844c0db2beeec9304492f/lib/active_storage/service/cloudinary_service.rb#L26

I was able to get around this by mokeypatching File.open like so:

```
class File
  def self.open(*args)
    if args[0].is_a?(StringIO)
      begin
        string = args[0]
        tmp = Tempfile.new
        tmp.binmode
        tmp.write string.read
        tmp.rewind
        args[0] = tmp
        string.rewind
      rescue StandardError
      end
    end

    file = super(*args)
    file
  end
end
```

But that is not a sustainable solution

**Comment by 0sc** [comment]
Thanks @MadonnaMat, I'll look into it. Can you share steps to reproduce?

**Comment by MadonnaMat** [comment]
img_loc = Tempfile.new(['cover', '.png'])
    MiniMagick::Tool::Convert.new do |i|
       i.size '510x780'
       i << 'xc:white'
       i.gravity 'North'
       i.geometry '+200 +100'
       i.pointsize '36'
       i.caption "\\n#{title}"
       i.composite img_loc.path
    end

    img_loc.rewind

    cover.attach(io: img_loc,
                 filename: "#{title.parameterize.underscore}.png",
                 content_type: 'image/png')
