### ISSUE TITLE
Define format of images in config

### ISSUE THREAD

**Issue by pkrawat1** [0sc/activestorage-cloudinary-service#7]
I want a fixed format like `webp` for the images that are uploaded. This would reduce my website image payloads.

I have use cloudinary service decorator for now to set the default format option to `webp`.

**Comment by 0sc** [comment]
Hmm ... we could update the cloudinary storage initializer to accept desired upload transformations such as this. I worry that having this could lead to conflicts with the activestorage expectations. 
For example, if a user sets a transformation to change the asset type from say `png` to `webp`, activestorage is unaware of this and still keeps tracking the asset as `image/png`. This could cause problems with some other helpful activestorage helper methods that depend on the information like `#previewable?`   🤔
